services:
  boardgame-app:
    # build: 
    #   context: .
    #   dockerfile: Dockerfile
    image: harbor.server.thweb.click/tthau/boardgame:v1
    pull_policy: always
    container_name: boardgame-app
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:h2:mem:testdb
      - SPRING_H2_CONSOLE_ENABLED=true
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8080/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s